trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: e2e_test          # ✅ Variable Group linked
  - name: NODE_VERSION
    value: '18.x'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npx cypress verify
    displayName: 'Verify Cypress'

  - script: npx cypress run --browser chrome
    displayName: 'Run Cypress API Tests'

  - task: PublishBuildArtifacts@1
    condition: always()
    inputs:
      pathToPublish: cypress
      artifactName: cypress-results
