import { CREATE_LOGIN_SESSION_MUTATION } from './authentication';
import { GET_CUSTOMER_LIST_QUERY, GET_CUSTOMER_DETAIL_QUERY } from './customer';
import { CREATE_SESSION_MUTATION, UPDATE_SESSION_MUTATION } from './session';
import { GET_METADATA_QUERY } from './metaData';

export {
  CREATE_LOGIN_SESSION_MUTATION,
  GET_CUSTOMER_LIST_QUERY,
  GET_CUSTOMER_DETAIL_QUERY,
  CREATE_SESSION_MUTATION,
  UPDATE_SESSION_MUTATION,
  GET_METADATA_QUERY,
};
